import { RscRankEntity } from '@/contexts/resources/infra/persistence/entities/games/base/rsc-ranks.entity';
import { logSection, seedIfNotExists } from '@/new_seeders/helpers/seeder-utils';
import { DataSource } from 'typeorm';


export async function seedRanks(dataSource: DataSource) {
  const repo = dataSource.getRepository(RscRankEntity);
  logSection('RANKS');

 const ranks: Partial<RscRankEntity>[] = [
    /* -------------------------------------------------------------------------- */
    /* 🧠 LEAGUE OF LEGENDS / TFT                                                */
    /* -------------------------------------------------------------------------- */
    { name: 'Iron IV', slug: 'lol-iron-4', division: 'Iron', tier: 'IV', order: 1, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fleague-of-legends%2Franks%2Firon.png?alt=media&token=19f00034-708d-4a46-bc8b-f564737ac7cf' },
    { name: 'Iron III', slug: 'lol-iron-3', division: 'Iron', tier: 'III', order: 2, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fleague-of-legends%2Franks%2Firon.png?alt=media&token=19f00034-708d-4a46-bc8b-f564737ac7cf' },
    { name: 'Iron II', slug: 'lol-iron-2', division: 'Iron', tier: 'II', order: 3, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fleague-of-legends%2Franks%2Firon.png?alt=media&token=19f00034-708d-4a46-bc8b-f564737ac7cf' },
    { name: 'Iron I', slug: 'lol-iron-1', division: 'Iron', tier: 'I', order: 4, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fleague-of-legends%2Franks%2Firon.png?alt=media&token=19f00034-708d-4a46-bc8b-f564737ac7cf' },
    { name: 'Bronze IV', slug: 'lol-bronze-4', division: 'Bronze', tier: 'IV', order: 5, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fleague-of-legends%2Franks%2Fbronze.png?alt=media&token=bfd1df37-a681-4b90-b3f3-ef70378ebf6e' },
    { name: 'Bronze III', slug: 'lol-bronze-3', division: 'Bronze', tier: 'III', order: 6, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fleague-of-legends%2Franks%2Fbronze.png?alt=media&token=bfd1df37-a681-4b90-b3f3-ef70378ebf6e' },
    { name: 'Bronze II', slug: 'lol-bronze-2', division: 'Bronze', tier: 'II', order: 7, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fleague-of-legends%2Franks%2Fbronze.png?alt=media&token=bfd1df37-a681-4b90-b3f3-ef70378ebf6e' },
    { name: 'Bronze I', slug: 'lol-bronze-1', division: 'Bronze', tier: 'I', order: 8, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fleague-of-legends%2Franks%2Fbronze.png?alt=media&token=bfd1df37-a681-4b90-b3f3-ef70378ebf6e' },
    { name: 'Silver IV', slug: 'lol-silver-4', division: 'Silver', tier: 'IV', order: 9, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fleague-of-legends%2Franks%2Fsilver.png?alt=media&token=82f732d0-e4e4-413c-b4c6-db9ac7781957' },
    { name: 'Silver III', slug: 'lol-silver-3', division: 'Silver', tier: 'III', order: 10, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fleague-of-legends%2Franks%2Fsilver.png?alt=media&token=82f732d0-e4e4-413c-b4c6-db9ac7781957' },
    { name: 'Silver II', slug: 'lol-silver-2', division: 'Silver', tier: 'II', order: 11, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fleague-of-legends%2Franks%2Fsilver.png?alt=media&token=82f732d0-e4e4-413c-b4c6-db9ac7781957' },
    { name: 'Silver I', slug: 'lol-silver-1', division: 'Silver', tier: 'I', order: 12, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fleague-of-legends%2Franks%2Fsilver.png?alt=media&token=82f732d0-e4e4-413c-b4c6-db9ac7781957' },
    { name: 'Gold IV', slug: 'lol-gold-4', division: 'Gold', tier: 'IV', order: 13, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fleague-of-legends%2Franks%2Fgold.png?alt=media&token=447ce4af-9d7d-4c85-b4c7-2ea19f7537df' },
    { name: 'Gold III', slug: 'lol-gold-3', division: 'Gold', tier: 'III', order: 14, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fleague-of-legends%2Franks%2Fgold.png?alt=media&token=447ce4af-9d7d-4c85-b4c7-2ea19f7537df' },
    { name: 'Gold II', slug: 'lol-gold-2', division: 'Gold', tier: 'II', order: 15, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fleague-of-legends%2Franks%2Fgold.png?alt=media&token=447ce4af-9d7d-4c85-b4c7-2ea19f7537df' },
    { name: 'Gold I', slug: 'lol-gold-1', division: 'Gold', tier: 'I', order: 16, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fleague-of-legends%2Franks%2Fgold.png?alt=media&token=447ce4af-9d7d-4c85-b4c7-2ea19f7537df' },
    { name: 'Platinum IV', slug: 'lol-platinum-4', division: 'Platinum', tier: 'IV', order: 17, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fleague-of-legends%2Franks%2Fplatinum.png?alt=media&token=6e87bb88-2ac9-4709-80aa-df5079bccc8e' },
    { name: 'Platinum III', slug: 'lol-platinum-3', division: 'Platinum', tier: 'III', order: 18, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fleague-of-legends%2Franks%2Fplatinum.png?alt=media&token=6e87bb88-2ac9-4709-80aa-df5079bccc8e' },
    { name: 'Platinum II', slug: 'lol-platinum-2', division: 'Platinum', tier: 'II', order: 19, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fleague-of-legends%2Franks%2Fplatinum.png?alt=media&token=6e87bb88-2ac9-4709-80aa-df5079bccc8e' },
    { name: 'Platinum I', slug: 'lol-platinum-1', division: 'Platinum', tier: 'I', order: 20, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fleague-of-legends%2Franks%2Fplatinum.png?alt=media&token=6e87bb88-2ac9-4709-80aa-df5079bccc8e' },
    { name: 'Emerald IV', slug: 'lol-emerald-4', division: 'Emerald', tier: 'IV', order: 21, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fleague-of-legends%2Franks%2Femerald.png?alt=media&token=241b85ce-c33f-4a5e-b1af-767d6a3a3376' },
    { name: 'Emerald III', slug: 'lol-emerald-3', division: 'Emerald', tier: 'III', order: 22, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fleague-of-legends%2Franks%2Femerald.png?alt=media&token=241b85ce-c33f-4a5e-b1af-767d6a3a3376' },
    { name: 'Emerald II', slug: 'lol-emerald-2', division: 'Emerald', tier: 'II', order: 23, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fleague-of-legends%2Franks%2Femerald.png?alt=media&token=241b85ce-c33f-4a5e-b1af-767d6a3a3376' },
    { name: 'Emerald I', slug: 'lol-emerald-1', division: 'Emerald', tier: 'I', order: 24, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fleague-of-legends%2Franks%2Femerald.png?alt=media&token=241b85ce-c33f-4a5e-b1af-767d6a3a3376' },
    { name: 'Diamond IV', slug: 'lol-diamond-4', division: 'Diamond', tier: 'IV', order: 25, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fleague-of-legends%2Franks%2Fdiamond.png?alt=media&token=b9b97d0f-cc0c-42b5-a7d4-f94ff4e2609f' },
    { name: 'Diamond III', slug: 'lol-diamond-3', division: 'Diamond', tier: 'III', order: 26, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fleague-of-legends%2Franks%2Fdiamond.png?alt=media&token=b9b97d0f-cc0c-42b5-a7d4-f94ff4e2609f' },
    { name: 'Diamond II', slug: 'lol-diamond-2', division: 'Diamond', tier: 'II', order: 27, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fleague-of-legends%2Franks%2Fdiamond.png?alt=media&token=b9b97d0f-cc0c-42b5-a7d4-f94ff4e2609f' },
    { name: 'Diamond I', slug: 'lol-diamond-1', division: 'Diamond', tier: 'I', order: 28, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fleague-of-legends%2Franks%2Fdiamond.png?alt=media&token=b9b97d0f-cc0c-42b5-a7d4-f94ff4e2609f' },
    { name: 'Master', slug: 'lol-master', division: 'Master', order: 29, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fleague-of-legends%2Franks%2Fmaster.png?alt=media&token=29be17d4-e3ac-460b-9361-fceb4c6c28f6' },
    { name: 'Grandmaster', slug: 'lol-grandmaster', division: 'Grandmaster', order: 30, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fleague-of-legends%2Franks%2Fgrand-master.png?alt=media&token=7042d21f-0e95-48fa-a205-a594be61c1cf' },
    { name: 'Challenger', slug: 'lol-challenger', division: 'Challenger', order: 31, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fleague-of-legends%2Franks%2Fchallenger.png?alt=media&token=acd2660b-c21e-4399-9040-89be235818ec' },

    /* -------------------------------------------------------------------------- */
    /* 🎯 VALORANT                                                               */
    /* -------------------------------------------------------------------------- */
    { name: 'Iron 1', slug: 'val-iron-1', division: 'Iron', tier: 'I', order: 1, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fvalorant%2Franks%2Firon.png?alt=media&token=dbe3c2f1-bb6c-43b0-a1da-b8a2447325d1' },
    { name: 'Iron 2', slug: 'val-iron-2', division: 'Iron', tier: 'II', order: 2, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fvalorant%2Franks%2Firon.png?alt=media&token=dbe3c2f1-bb6c-43b0-a1da-b8a2447325d1' },
    { name: 'Iron 3', slug: 'val-iron-3', division: 'Iron', tier: 'III', order: 3, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fvalorant%2Franks%2Firon.png?alt=media&token=dbe3c2f1-bb6c-43b0-a1da-b8a2447325d1' },
    { name: 'Bronze 1', slug: 'val-bronze-1', division: 'Bronze', tier: 'I', order: 4, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fvalorant%2Franks%2Fbronze.png?alt=media&token=48bf3cd6-ea23-4233-9061-1e24abe2fe73' },
    { name: 'Bronze 2', slug: 'val-bronze-2', division: 'Bronze', tier: 'II', order: 5, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fvalorant%2Franks%2Fbronze.png?alt=media&token=48bf3cd6-ea23-4233-9061-1e24abe2fe73' },
    { name: 'Bronze 3', slug: 'val-bronze-3', division: 'Bronze', tier: 'III', order: 6, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fvalorant%2Franks%2Fbronze.png?alt=media&token=48bf3cd6-ea23-4233-9061-1e24abe2fe73' },
    { name: 'Silver 1', slug: 'val-silver-1', division: 'Silver', tier: 'I', order: 7, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fvalorant%2Franks%2Fsilver.png?alt=media&token=44e1e4b2-1c95-48ff-9c30-5fbb2fe3f17d' },
    { name: 'Silver 2', slug: 'val-silver-2', division: 'Silver', tier: 'II', order: 8, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fvalorant%2Franks%2Fsilver.png?alt=media&token=44e1e4b2-1c95-48ff-9c30-5fbb2fe3f17d' },
    { name: 'Silver 3', slug: 'val-silver-3', division: 'Silver', tier: 'III', order: 9, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fvalorant%2Franks%2Fsilver.png?alt=media&token=44e1e4b2-1c95-48ff-9c30-5fbb2fe3f17d' },
    { name: 'Gold 1', slug: 'val-gold-1', division: 'Gold', tier: 'I', order: 10, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fvalorant%2Franks%2Fgold.png?alt=media&token=aedddc6b-d55a-4b91-8240-a00654ce231e' },
    { name: 'Gold 2', slug: 'val-gold-2', division: 'Gold', tier: 'II', order: 11, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fvalorant%2Franks%2Fgold.png?alt=media&token=aedddc6b-d55a-4b91-8240-a00654ce231e' },
    { name: 'Gold 3', slug: 'val-gold-3', division: 'Gold', tier: 'III', order: 12, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fvalorant%2Franks%2Fgold.png?alt=media&token=aedddc6b-d55a-4b91-8240-a00654ce231e' },
    { name: 'Platinum 1', slug: 'val-platinum-1', division: 'Platinum', tier: 'I', order: 13, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fvalorant%2Franks%2Fplatinum.png?alt=media&token=03d34caf-21e0-445f-bb35-f000b791e60e' },
    { name: 'Platinum 2', slug: 'val-platinum-2', division: 'Platinum', tier: 'II', order: 14, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fvalorant%2Franks%2Fplatinum.png?alt=media&token=03d34caf-21e0-445f-bb35-f000b791e60e' },
    { name: 'Platinum 3', slug: 'val-platinum-3', division: 'Platinum', tier: 'III', order: 15, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fvalorant%2Franks%2Fplatinum.png?alt=media&token=03d34caf-21e0-445f-bb35-f000b791e60e' },
    { name: 'Diamond 1', slug: 'val-diamond-1', division: 'Diamond', tier: 'I', order: 16, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fvalorant%2Franks%2Fdiamond.png?alt=media&token=95f67ea0-c796-4398-b21e-dc43b1a1efd3' },
    { name: 'Diamond 2', slug: 'val-diamond-2', division: 'Diamond', tier: 'II', order: 17, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fvalorant%2Franks%2Fdiamond.png?alt=media&token=95f67ea0-c796-4398-b21e-dc43b1a1efd3' },
    { name: 'Diamond 3', slug: 'val-diamond-3', division: 'Diamond', tier: 'III', order: 18, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fvalorant%2Franks%2Fdiamond.png?alt=media&token=95f67ea0-c796-4398-b21e-dc43b1a1efd3' },
    { name: 'Ascendant 1', slug: 'val-ascendant-1', division: 'Ascendant', tier: 'I', order: 19, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fvalorant%2Franks%2Fascendant.png?alt=media&token=f492cb72-abf4-439d-bc59-673b009294c5' },
    { name: 'Ascendant 2', slug: 'val-ascendant-2', division: 'Ascendant', tier: 'II', order: 20, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fvalorant%2Franks%2Fascendant.png?alt=media&token=f492cb72-abf4-439d-bc59-673b009294c5' },
    { name: 'Ascendant 3', slug: 'val-ascendant-3', division: 'Ascendant', tier: 'III', order: 21, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fvalorant%2Franks%2Fascendant.png?alt=media&token=f492cb72-abf4-439d-bc59-673b009294c5' },
    { name: 'Immortal 1', slug: 'val-immortal-1', division: 'Immortal', tier: 'I', order: 22, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fvalorant%2Franks%2Fimmortal.png?alt=media&token=29e41342-58f8-4169-acd0-94479ce6d2da' },
    { name: 'Immortal 2', slug: 'val-immortal-2', division: 'Immortal', tier: 'II', order: 23, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fvalorant%2Franks%2Fimmortal.png?alt=media&token=29e41342-58f8-4169-acd0-94479ce6d2da' },
    { name: 'Immortal 3', slug: 'val-immortal-3', division: 'Immortal', tier: 'III', order: 24, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fvalorant%2Franks%2Fimmortal.png?alt=media&token=29e41342-58f8-4169-acd0-94479ce6d2da' },
    { name: 'Radiant', slug: 'val-radiant', division: 'Radiant', order: 25, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fvalorant%2Franks%2Fradiant.png?alt=media&token=d12b5392-2688-403e-b985-4746d055bed1' },

    /* -------------------------------------------------------------------------- */
    /* ⚽ Rocket League                                                               */
    /* -------------------------------------------------------------------------- */
    { name: 'Bronze I', slug: 'rl-bronze-i', division: 'Bronze', tier: 'I', order: 1, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Frocket-league%2Franks%2Fbronze.png?alt=media&token=c65c6e89-7926-4cff-ad08-93d364cfb77e' },
    { name: 'Bronze II', slug: 'rl-bronze-ii', division: 'Bronze', tier: 'II', order: 2, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Frocket-league%2Franks%2Fbronze.png?alt=media&token=c65c6e89-7926-4cff-ad08-93d364cfb77e' },
    { name: 'Bronze III', slug: 'rl-bronze-iii', division: 'Bronze', tier: 'III', order: 3, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Frocket-league%2Franks%2Fbronze.png?alt=media&token=c65c6e89-7926-4cff-ad08-93d364cfb77e' },
    { name: 'Silver I', slug: 'rl-silver-i', division: 'Silver', tier: 'I', order: 4, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Frocket-league%2Franks%2Fsilver.png?alt=media&token=881f4e31-a847-49f0-8ce8-5f6dc441676a' },
    { name: 'Silver II', slug: 'rl-silver-ii', division: 'Silver', tier: 'II', order: 5, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Frocket-league%2Franks%2Fsilver.png?alt=media&token=881f4e31-a847-49f0-8ce8-5f6dc441676a' },
    { name: 'Silver III', slug: 'rl-silver-iii', division: 'Silver', tier: 'III', order: 6, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Frocket-league%2Franks%2Fsilver.png?alt=media&token=881f4e31-a847-49f0-8ce8-5f6dc441676a' },
    { name: 'Gold I', slug: 'rl-gold-i', division: 'Gold', tier: 'I', order: 7, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Frocket-league%2Franks%2Fgold.png?alt=media&token=63bd3168-096a-4be7-b6bb-8c40239b1583' },
    { name: 'Gold II', slug: 'rl-gold-ii', division: 'Gold', tier: 'II', order: 8, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Frocket-league%2Franks%2Fgold.png?alt=media&token=63bd3168-096a-4be7-b6bb-8c40239b1583' },
    { name: 'Gold III', slug: 'rl-gold-iii', division: 'Gold', tier: 'III', order: 9, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Frocket-league%2Franks%2Fgold.png?alt=media&token=63bd3168-096a-4be7-b6bb-8c40239b1583' },
    { name: 'Platinum I', slug: 'rl-platinum-i', division: 'Platinum', tier: 'I', order: 10, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Frocket-league%2Franks%2Fplatinum.png?alt=media&token=793c86f8-bad6-4f0a-b82f-c371e8a5353b' },
    { name: 'Platinum II', slug: 'rl-platinum-ii', division: 'Platinum', tier: 'II', order: 11, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Frocket-league%2Franks%2Fplatinum.png?alt=media&token=793c86f8-bad6-4f0a-b82f-c371e8a5353b' },
    { name: 'Platinum III', slug: 'rl-platinum-iii', division: 'Platinum', tier: 'III', order: 12, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Frocket-league%2Franks%2Fplatinum.png?alt=media&token=793c86f8-bad6-4f0a-b82f-c371e8a5353b' },
    { name: 'Diamond I', slug: 'rl-diamond-i', division: 'Diamond', tier: 'I', order: 13, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Frocket-league%2Franks%2Fdiamond.png?alt=media&token=96234f3d-6884-42d8-b71d-2b85d42410a7' },
    { name: 'Diamond II', slug: 'rl-diamond-ii', division: 'Diamond', tier: 'II', order: 14, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Frocket-league%2Franks%2Fdiamond.png?alt=media&token=96234f3d-6884-42d8-b71d-2b85d42410a7' },
    { name: 'Diamond III', slug: 'rl-diamond-iii', division: 'Diamond', tier: 'III', order: 15, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Frocket-league%2Franks%2Fdiamond.png?alt=media&token=96234f3d-6884-42d8-b71d-2b85d42410a7' },
    { name: 'Champion I', slug: 'rl-champion-i', division: 'Champion', tier: 'I', order: 16, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Frocket-league%2Franks%2Fchampion.png?alt=media&token=deb3ca50-4a99-4342-8256-3655eb8bd8e5' },
    { name: 'Champion II', slug: 'rl-champion-ii', division: 'Champion', tier: 'II', order: 17, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Frocket-league%2Franks%2Fchampion.png?alt=media&token=deb3ca50-4a99-4342-8256-3655eb8bd8e5' },
    { name: 'Champion III', slug: 'rl-champion-iii', division: 'Champion', tier: 'III', order: 18, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Frocket-league%2Franks%2Fchampion.png?alt=media&token=deb3ca50-4a99-4342-8256-3655eb8bd8e5' },
    { name: 'Grand Champion I', slug: 'rl-grand-champion-i', division: 'Grand Champion', tier: 'I', order: 19, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Frocket-league%2Franks%2Fgrand-champion.png?alt=media&token=c27299aa-8015-4b13-bbb0-8d5adaa02a67' },
    { name: 'Grand Champion II', slug: 'rl-grand-champion-ii', division: 'Grand Champion', tier: 'II', order: 20, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Frocket-league%2Franks%2Fgrand-champion.png?alt=media&token=c27299aa-8015-4b13-bbb0-8d5adaa02a67' },
    { name: 'Grand Champion III', slug: 'rl-grand-champion-iii', division: 'Grand Champion', tier: 'III', order: 21, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Frocket-league%2Franks%2Fgrand-champion.png?alt=media&token=c27299aa-8015-4b13-bbb0-8d5adaa02a67' },
    { name: 'Supersonic Legend', slug: 'rl-supersonic-legend', division: 'Supersonic Legend', order: 22, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Frocket-league%2Franks%2Fsupersonic-legend.png?alt=media&token=0d761669-1fb4-4768-979d-ebedc6b5a14a' },
  
    /* -------------------------------------------------------------------------- */
    /* Fortnite                                                               */
    /* -------------------------------------------------------------------------- */
    { name: 'Bronze I', slug: 'ftn-bronze-i', division: 'Bronze', tier: 'I', order: 1, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Ffortnite%2Franks%2Fbronze.png?alt=media&token=f24c3662-a301-4d2f-aa48-29721f9b7d63' },
    { name: 'Bronze II', slug: 'ftn-bronze-ii', division: 'Bronze', tier: 'II', order: 2, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Ffortnite%2Franks%2Fbronze.png?alt=media&token=f24c3662-a301-4d2f-aa48-29721f9b7d63' },
    { name: 'Bronze III', slug: 'ftn-bronze-iii', division: 'Bronze', tier: 'III', order: 3, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Ffortnite%2Franks%2Fbronze.png?alt=media&token=f24c3662-a301-4d2f-aa48-29721f9b7d63' },
    { name: 'Silver I', slug: 'ftn-silver-i', division: 'Silver', tier: 'I', order: 4, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Ffortnite%2Franks%2Fsilver.png?alt=media&token=c8898525-3750-4628-a5f5-0866885e325d' },
    { name: 'Silver II', slug: 'ftn-silver-ii', division: 'Silver', tier: 'II', order: 5, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Ffortnite%2Franks%2Fsilver.png?alt=media&token=c8898525-3750-4628-a5f5-0866885e325d' },
    { name: 'Silver III', slug: 'ftn-silver-iii', division: 'Silver', tier: 'III', order: 6, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Ffortnite%2Franks%2Fsilver.png?alt=media&token=c8898525-3750-4628-a5f5-0866885e325d' },
    { name: 'Gold I', slug: 'ftn-gold-i', division: 'Gold', tier: 'I', order: 7, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Ffortnite%2Franks%2Fgold.png?alt=media&token=d5c1fbd1-3480-4235-8344-f3ccfee22255' },
    { name: 'Gold II', slug: 'ftn-gold-ii', division: 'Gold', tier: 'II', order: 8, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Ffortnite%2Franks%2Fgold.png?alt=media&token=d5c1fbd1-3480-4235-8344-f3ccfee22255' },
    { name: 'Gold III', slug: 'ftn-gold-iii', division: 'Gold', tier: 'III', order: 9, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Ffortnite%2Franks%2Fgold.png?alt=media&token=d5c1fbd1-3480-4235-8344-f3ccfee22255' },
    { name: 'Platinum I', slug: 'ftn-platinum-i', division: 'Platinum', tier: 'I', order: 10, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Ffortnite%2Franks%2Fplatinum.png?alt=media&token=b9f3e692-418e-46a0-80ff-48e48dd7f00e' },
    { name: 'Platinum II', slug: 'ftn-platinum-ii', division: 'Platinum', tier: 'II', order: 11, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Ffortnite%2Franks%2Fplatinum.png?alt=media&token=b9f3e692-418e-46a0-80ff-48e48dd7f00e' },
    { name: 'Platinum III', slug: 'ftn-platinum-iii', division: 'Platinum', tier: 'III', order: 12, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Ffortnite%2Franks%2Fplatinum.png?alt=media&token=b9f3e692-418e-46a0-80ff-48e48dd7f00e' },
    { name: 'Diamond I', slug: 'ftn-diamond-i', division: 'Diamond', tier: 'I', order: 13, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Ffortnite%2Franks%2Fdiamond.png?alt=media&token=2e4cccf8-0f5c-46a8-a9dd-22f7fa9380b0' },
    { name: 'Diamond II', slug: 'ftn-diamond-ii', division: 'Diamond', tier: 'II', order: 14, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Ffortnite%2Franks%2Fdiamond.png?alt=media&token=2e4cccf8-0f5c-46a8-a9dd-22f7fa9380b0' },
    { name: 'Diamond III', slug: 'ftn-diamond-iii', division: 'Diamond', tier: 'III', order: 15, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Ffortnite%2Franks%2Fdiamond.png?alt=media&token=2e4cccf8-0f5c-46a8-a9dd-22f7fa9380b0' },
    { name: 'Elite', slug: 'ftn-elite', division: 'Elite', tier: null, order: 16, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Ffortnite%2Franks%2F%C3%A9lite.png?alt=media&token=4319e6ad-ffea-4247-a41b-127500338830' },
    { name: 'Champion', slug: 'ftn-champion', division: 'Champion', tier: null, order: 17, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Ffortnite%2Franks%2Fchampion.png?alt=media&token=092a4143-0c0c-473e-a1ba-dfc74aa9f98c' },
    { name: 'Unreal', slug: 'ftn-unreal', division: 'Unreal', tier: null, order: 18, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Ffortnite%2Franks%2Funreal.png?alt=media&token=f1289d8f-517b-4c48-b275-b4a553016484' },
  
    /* -------------------------------------------------------------------------- */
    /* Brawlstar                                                               */
    /* -------------------------------------------------------------------------- */
    { name: 'Bronze I', slug: 'brawl-bronze-i', division: 'Bronze', tier: 'I', order: 1, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fbrawl-stars%2Franks%2Fbronze.png?alt=media&token=0d825c7f-93cb-40a4-bcab-2ee2ca0da27a' },
    { name: 'Bronze II', slug: 'brawl-bronze-ii', division: 'Bronze', tier: 'II', order: 2, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fbrawl-stars%2Franks%2Fbronze.png?alt=media&token=0d825c7f-93cb-40a4-bcab-2ee2ca0da27a' },
    { name: 'Bronze III', slug: 'brawl-bronze-iii', division: 'Bronze', tier: 'III', order: 3, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fbrawl-stars%2Franks%2Fbronze.png?alt=media&token=0d825c7f-93cb-40a4-bcab-2ee2ca0da27a' },
    { name: 'Silver I', slug: 'brawl-silver-i', division: 'Silver', tier: 'I', order: 4, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fbrawl-stars%2Franks%2Fsilver.png?alt=media&token=09de2223-1c62-4a3a-8fe4-5eec5776061f' },
    { name: 'Silver II', slug: 'brawl-silver-ii', division: 'Silver', tier: 'II', order: 5, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fbrawl-stars%2Franks%2Fsilver.png?alt=media&token=09de2223-1c62-4a3a-8fe4-5eec5776061f' },
    { name: 'Silver III', slug: 'brawl-silver-iii', division: 'Silver', tier: 'III', order: 6, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fbrawl-stars%2Franks%2Fsilver.png?alt=media&token=09de2223-1c62-4a3a-8fe4-5eec5776061f' },
    { name: 'Gold I', slug: 'brawl-gold-i', division: 'Gold', tier: 'I', order: 7, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fbrawl-stars%2Franks%2Fgold.png?alt=media&token=2309ed63-b060-4c70-af8b-1626924217df' },
    { name: 'Gold II', slug: 'brawl-gold-ii', division: 'Gold', tier: 'II', order: 8, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fbrawl-stars%2Franks%2Fgold.png?alt=media&token=2309ed63-b060-4c70-af8b-1626924217df' },
    { name: 'Gold III', slug: 'brawl-gold-iii', division: 'Gold', tier: 'III', order: 9, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fbrawl-stars%2Franks%2Fgold.png?alt=media&token=2309ed63-b060-4c70-af8b-1626924217df' },
    { name: 'Diamond I', slug: 'brawl-diamond-i', division: 'Diamond', tier: 'I', order: 10, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fbrawl-stars%2Franks%2Fdiamond.png?alt=media&token=65fd1073-30ab-4be5-bc31-8c4210873fd5' },
    { name: 'Diamond II', slug: 'brawl-diamond-ii', division: 'Diamond', tier: 'II', order: 11, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fbrawl-stars%2Franks%2Fdiamond.png?alt=media&token=65fd1073-30ab-4be5-bc31-8c4210873fd5' },
    { name: 'Diamond III', slug: 'brawl-diamond-iii', division: 'Diamond', tier: 'III', order: 12, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fbrawl-stars%2Franks%2Fdiamond.png?alt=media&token=65fd1073-30ab-4be5-bc31-8c4210873fd5' },
    { name: 'Mythic I', slug: 'brawl-mythic-i', division: 'Mythic', tier: 'I', order: 13, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fbrawl-stars%2Franks%2FMythic.png?alt=media&token=d6258651-9574-4447-b59c-d6762fe4024a' },
    { name: 'Mythic II', slug: 'brawl-mythic-ii', division: 'Mythic', tier: 'II', order: 14, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fbrawl-stars%2Franks%2FMythic.png?alt=media&token=d6258651-9574-4447-b59c-d6762fe4024a' },
    { name: 'Mythic III', slug: 'brawl-mythic-iii', division: 'Mythic', tier: 'III', order: 15, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fbrawl-stars%2Franks%2FMythic.png?alt=media&token=d6258651-9574-4447-b59c-d6762fe4024a' },
    { name: 'Legendary I', slug: 'brawl-legendary-i', division: 'Legendary', tier: 'I', order: 16, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fbrawl-stars%2Franks%2Flegendary.png?alt=media&token=a9360547-e300-49d2-98b8-82e87a30ffec' },
    { name: 'Legendary II', slug: 'brawl-legendary-ii', division: 'Legendary', tier: 'II', order: 17, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fbrawl-stars%2Franks%2Flegendary.png?alt=media&token=a9360547-e300-49d2-98b8-82e87a30ffec' },
    { name: 'Legendary III', slug: 'brawl-legendary-iii', division: 'Legendary', tier: 'III', order: 18, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fbrawl-stars%2Franks%2Flegendary.png?alt=media&token=a9360547-e300-49d2-98b8-82e87a30ffec' },
    { name: 'Master', slug: 'brawl-master', division: 'Master', tier: null, order: 19, icon: 'https://firebasestorage.googleapis.com/v0/b/gamerlink-1d7db.firebasestorage.app/o/images%2Fgames%2Fbrawl-stars%2Franks%2Fmasters.png?alt=media&token=499f8d7f-1d37-48e2-a215-cb4d8330c5df' },
  ];

  for (const r of ranks) {
    await seedIfNotExists(repo, { slug: r.slug }, r);
  }

  console.log('✅ Ranks seeded successfully!');
}
